### PR TITLE
ENH: seqcoll.to_fasta supports block_size

### PR DESCRIPTION
**Pull request by rmcar17**
Addresses #1795

### CODE REVIEW

**Comment by rmcar17** [comment]
Looks like Python 3.9 is not supported by setup-python on macos-14 (https://github.com/actions/setup-python/issues/850).
A result of the [rollout to macos-14](https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/), may need to downgrade to macos-13 for now,

**Comment by ZeroIntensity** [comment]
`macos-12` is what `macos-latest` used to point to, maybe it's a better idea to just use that.

**Comment by rmcar17** [comment]
Thanks Zero! Looks like it's been resolved now anyway, so we'll be moving back to latest.

**Review by GavinHuttley — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
