### PR TITLE
API: Nested models now reflect their appropriate name. #941

### PR DESCRIPTION
**Pull request by jamesmartini**
Nested models now reflect their appropriate name, while base models retain their base name.

### CODE REVIEW

**Review by GavinHuttley — CHANGES_REQUESTED** [review]
Thanks heaps for this. Can you add a new test method to the `CannedModelsTest` class in`tests/test_evolve/test_models.py`, e.g.

```python
def test_model_names(self):
    """name attribute matches model name"""
    for model_name in models:
        model = get_model(model_name)
        self.assertEqual(model.name, model_name)    
```
There may be other models that fail this!

**Comment by jamesmartini** [comment]
I had a problem with that test: The discrete time substitution model 'DT' substracts the motif_length from its name 'DT'. Two proposed solutions: 
1. Create a separate test for discrete models.
2. Or create an 'effective_name' argument in the kw variable for the DT model which tracks DT-motif_length and leaves 'name' as 'DT'.

**Comment by GavinHuttley** [comment]
There's a third option, if `model_name` starts with "DT", only check that `model.name` starts with "DT"

**Comment by jamesmartini** [comment]
Implementing an explicit check for "DT" in model.name reveals there is also another model AH96 which has name "AH96_mtREV24". The following proposed test checks that if model X has a name different to X then it checks that the name satisfies XZ for any string Z, otherwise checks equality:

```
    def test_model_names(self):
        """name attribute matches model name"""
        for model_name in models:
            model = get_model(model_name)
            if model.name is not model_name:
                self.assertTrue(model.name.startswith(model_name))
            else:
                self.assertEqual(model.name, model_name)
```

**Comment by GavinHuttley** [comment]
Thanks heaps James! I played around a bit trying to simplify things and wound back pretty much where you were. Whoops!

**Comment by jamesmartini** [comment]
> Thanks heaps James! I played around a bit trying to simplify things and wound back pretty much where you were. Whoops!

I really appreciate the detail and feedback. Cheers Gavin!

**Pull request merged**
