### PR TITLE
Add a check that the repo is cogent/cogent3

### LINKED ISSUE #1427: linter workflow action causes problems in forked repositories
The linter workflow action that runs black and isort on a push of new code into any branch but master results in an error in any fork of the repository where workflow actions do not have write rights to the repository. 

eg:

```
Error: Pushing to https://github.com/KatherineCaley/cogent3
remote: Permission to KatherineCaley/cogent3.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/KatherineCaley/cogent3/': The requested URL returned error: 403
```

### PR DESCRIPTION
**Pull request by khiron**
fixes #1427

### CODE REVIEW

**Comment by khiron** [comment]
@GavinHuttley and @KatherineCaley I don't get this issue on my fork.  I can't check that this addresses the problem of workflow actions not having write access to my repository, but as best I can tell it should.  When you get a moment please try making the change to the linters.yml in .github/workflow on your fork to confirm that the problem resolves.

**Comment by KatherineCaley** [comment]
@khiron I did a test push with the changes to linters.yml, and the run still fails, check the commit here: https://github.com/KatherineCaley/cogent3/actions/runs/4942256650/jobs/8835619192#step:8:126

Let me know if you want me to try another push.

**Comment by KatherineCaley** [comment]
@khiron I did a test push with the changes to linters.yml, and the run still fails, check the commit here: https://github.com/KatherineCaley/cogent3/actions/runs/4942256650/jobs/8835619192#step:8:126

Would you like me to try another push?

**Comment by khiron** [comment]
No that's enough for me. Thanks

**Comment by khiron** [comment]
@KatherineCaley this latest change might fix the problem

**Comment by KatherineCaley** [comment]
i think success!!!
https://github.com/KatherineCaley/cogent3/actions/runs/4942684445

**Pull request merged**
